# Generated by Django 2.1.5 on 2019-08-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='номер автомобиля')),
                ('car_mark', models.CharField(max_length=30, verbose_name='марка автомобиля')),
                ('car_model', models.CharField(max_length=50, verbose_name='модель автомобиля')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_for_invite', models.IntegerField(verbose_name='реф номер для приглашений')),
                ('user_number_for_invite', models.IntegerField(verbose_name='реф номер пригласителя')),
                ('invited_link', models.CharField(max_length=50, verbose_name='ссылка на того, кто пригласил')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('lastname', models.CharField(max_length=50, verbose_name='отчество')),
                ('phone', models.SmallIntegerField(blank=True, null=True, verbose_name='телефон')),
                ('balance', models.CharField(blank=True, max_length=50, verbose_name='баланс')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.User', verbose_name='img_driver')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.User', verbose_name='car_driver'),
        ),
    ]
