# Generated by Django 2.1.5 on 2019-08-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={},
        ),
    ]
