# Generated by Django 2.1.5 on 2019-08-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_auto_20190808_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='invited_link',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
